### ISSUE TITLE
Could not pass event PlayerInteractEvent to MyChunk

### ISSUE THREAD

**Issue by d-stephane** [dwilson390/MyChunk#4]
I have a problem with this version of MyChunk:

	 [01:36:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MyChunk v2.6
	org.bukkit.event.EventException
		at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Bukkit-e91aed8]
		at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-e91aed8]
		at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-e91aed8]
		at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-e91aed8]
		at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:210) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:462) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:705) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-e91aed8]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
		at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
		at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:676) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit.jar:git-Bukkit-e91aed8]
		at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit.jar:git-Bukkit-e91aed8]
		at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
	Caused by: java.lang.NullPointerException
		at me.ellbristow.mychunk.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:309) ~[?:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
		at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
		at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-Bukkit-e91aed8]
		... 17 more

Server version is CraftBukkit 1.8.7 running the following plugins:

WorldEdit v6.1.1-SNAPSHOT;3394-9a65bdb7
WorldGuard v6.0.0
MassiveCore v2.8.0
Factions v2.8.0
Multiverse-Core v2.5-b691
Multiverse-Portals v2.5-b699
Multiverse-SignPortals v2.5-b679
Multiverse-EssentialsSupport v2.5-b3

I have also tried with only MyChunk installed on the server as well as testing with CraftBukkit 1.8.3.

**Comment by d-stephane** [comment]
I just tested with only Mychunk (without any plugin) : same problem

**Comment by dwilson390** [comment]
Thanks for reporting this, I will work on a fix today.

**Comment by dwilson390** [comment]
Fixed in latest release, please update: https://github.com/dwilson390/MyChunk/releases/tag/v1.6.1

**Comment by d-stephane** [comment]
Thank but it's not ok :-(
My log :
'
[17:51:37] [Server thread/INFO]: Starting minecraft server version 1.8.7
[17:51:37] [Server thread/INFO]: Loading properties
[17:51:37] [Server thread/INFO]: Default game type: SURVIVAL
[17:51:37] [Server thread/INFO]: Generating keypair
[17:51:37] [Server thread/INFO]: Starting Minecraft server on 192.168.1.10:25565
[17:51:37] [Server thread/INFO]: Using epoll channel type
[17:51:37] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-e91aed8 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
[17:51:39] [Server thread/ERROR]: Could not load 'plugins/MyChunk-1.6.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/ellbristow/mychunk/MyChunk : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit.jar:git-Bukkit-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:507) [craftbukkit.jar:git-Bukkit-e91aed8]
        at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]
Caused by: java.lang.UnsupportedClassVersionError: me/ellbristow/mychunk/MyChunk : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_25]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:792) ~[?:1.7.0_25]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_25]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_25]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_25]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_25]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_25]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_25]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_25]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.7.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.7.0_25]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_25]
        at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_25]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-e91aed8]
        ... 9 more
'

**Comment by dwilson390** [comment]
Please update to Java 8.

**Comment by d-stephane** [comment]
java update is ok :
`stephane@dagda:/home/minecraft$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK 64-Bit Server VM (build 25.66-b01, mixed mode)`

And now, after test :
`[22:54:08] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MyChunk v2.6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Bukkit-53fac9f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:210) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:462) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:728) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit.jar:git-Bukkit-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit.jar:git-Bukkit-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
	at me.ellbristow.mychunk.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:309) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit.jar:git-Bukkit-53fac9f]
	... 17 more
`

**Comment by dwilson390** [comment]
I see, the same issue seems to be arising. What actions are performed before this error happens? For example, a player could enter a claimed chunk or a player tried to open a chest in a protected chunks.

**Comment by d-stephane** [comment]
I just changed my java version. now, i have :
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Same problem.
-> the problem comes when a player opens a chest, he can open the chest and take items
(sorry for my bad english...)

**Comment by d-stephane** [comment]
player "test1" connect
player "test1" claim chunk : OK
player "test2" connect
player "test2" attempts to open chest in chunk of player "test2" : not possible, locked : OK
player "test1" disconnect
player "test2" attempts to open chest in chunk of player "test2" : possible, not locked : ERROR

**Comment by dwilson390** [comment]
I better understand the issue now. This error arises when a player attempts to access a chest of an offline player.

Thanks for reporting this, I hope to push a commit tonight which should fix this issue.

**Comment by dwilson390** [comment]
I have compiled this for you. Could you please try this plugin? 

You can download a compiled version of this plugin from here: https://files.dwilson.me.uk/MyChunk-1.6.1.jar

**Comment by dwilson390** [comment]
Just an update: tested this on a server. It seems the latest version (which I provided above) does not allow the opening of chest which belong to offline players.

This should hopefully fix the issue.

**Comment by d-stephane** [comment]
Everything works fine now, a big thank for your help, it's very cool :-)

**Comment by dwilson390** [comment]
Good to hear, also keep an eye out for a name change compatible version of this plugin I will be releasing later this, or early next month.

More information here: http://dev.bukkit.org/bukkit-plugins/mychunk/#c566
